"""initial tenant schema

Revision ID: c34bd55b3ea7
Revises: 
Create Date: 2026-04-06 11:44:12.035100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34bd55b3ea7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExpenseCategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Season',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_season_year_month')
    )
    op.create_table('Expense',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('expenseDate', sa.Date(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('seasonId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['ExpenseCategory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seasonId'], ['Season.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Importe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=True),
    sa.Column('importeDate', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balanceAfter', sa.Float(), nullable=True),
    sa.Column('seasonId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seasonId'], ['Season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Importe')
    op.drop_table('Expense')
    op.drop_table('Season')
    op.drop_table('ExpenseCategory')
    # ### end Alembic commands ###
