import os

MYSQLUSERNAME = os.environ["WALLET_TRACKER_DB_USER"]
MYSQLPASSWORD = os.environ["WALLET_TRACKER_DB_PASSWORD"]
MYSQLHOST = os.environ["WALLET_TRACKER_DB_HOST"]
MYSQLDBNAME = os.environ["WALLET_TRACKER_DB_NAME"]
SECRET = os.environ["WALLET_TRACKER_SECRET"]