import os

DATABASE_PASSWORD = os.environ["DATABASE_ROOT_PASSWORD"]
DATABASE_NAME = os.environ["DATABASE_NAME"]
DATABASE_USERNAME = os.environ["WALLET_TRACKER_DB_USER"]
DATABASE_HOST = os.environ["WALLET_TRACKER_DB_HOST"]
SECRET = os.environ["WALLET_TRACKER_SECRET"]
ENABLE_REGISTER = os.environ.get("ENABLE_REGISTER", "false")
