import os

MYSQLPASSWORD = os.environ["MYSQL_ROOT_PASSWORD"]
MYSQLDBNAME = os.environ["MYSQL_DATABASE"]
MYSQLUSERNAME = os.environ["WALLET_TRACKER_DB_USER"]
MYSQLHOST = os.environ["WALLET_TRACKER_DB_HOST"]
SECRET = os.environ["WALLET_TRACKER_SECRET"]
