class Messages:
    INTERNAL_ERROR = "Internal server error"
    INVALID_REQUEST = "Invalid request"
class UserMessages:
    CREATED = "User created successfully"
    USER_NOT_FOUND = "User not found"
class TokenMessages:
    MISSING = "Missing token"
    EXPIRED = "Expired token"
    INVALID = "Invalid token"
class AuthMessages:
    AUTH_ERROR = "Authorization error"
    LOGGED_IN = "Logged in successfully"
    FETCHED_SERVER_PUB_KEY = "Fetched server's public key successfully"
    ASSIGNED_SERVER_CLIENT_KEY = "Assigned client's public key successfully"
    ALREADY_EXISTS = "User already exists"
    DECRYPTION_FAILED = "Decryption process failed"
    ENCRYPTION_FAILED = "Encryption process failed"
    SIGNATURE_FAILED = "Signature process failed"
    VERIFICATION_FAILED = "Signature verification process failed"
    PRIVATE_KEY_FAILED = "Private key generation failed"
    PUBLIC_KEY_FAILED = "Public key generation failed"
    PAIRED_KEYS_FAILED = "Paired keys generation failed"
    INVALID_KEY = "Invalid key"
    INVALID_HEADERS = "Invalid headers"
    INVALID_PAYLOAD = "Invalid payload"
class MultitenantMessages:
    INIT_TENANT_FAILED = "Tenant initialisation failed"
class ExpenseCategoryMessages:
    NOT_FOUND = "ExpenseCategory not found"
    FETCHED = "ExpenseCategory fetched successfully"
    FETCHED_PLURAL = "ExpenseCategories fetched successfully"
    CREATED = "ExpenseCategory created successfully"
    DELETED = "ExpenseCategory deleted successfully"
    MODIFIED = "ExpenseCategory modified successfully"
class ExpenseMessages:
    NOT_FOUND = "Expense not found"
    FETCHED = "Expense fetched successfully"
    FETCHED_PLURAL = "Expenses fetched successfully"
    CREATED = "Expense created successfully"
    DELETED = "Expense deleted successfully"
    MODIFIED = "Expense modified successfully"