name: CD

on:
  push:
    branches: [main]

jobs:
  trigger-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.downops.win
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/wallettracker/backend JENKINS_API_TOKEN ;
            secret/data/wallettracker/backend JENKINS_BASE_URL ;
            secret/data/wallettracker/backend JENKINS_CD_SECRET ;
            secret/data/wallettracker/backend JENKINS_USERNAME

      - name: Trigger Jenkins Wallet Tracker CD
        env:
          GIT_BRANCH: main
        run: |
          curl -u "${{ env.JENKINS_USERNAME }}:${{ env.JENKINS_API_TOKEN }}" \
          "https://${{ env.JENKINS_BASE_URL }}/generic-webhook-trigger/invoke" \
          -H "Authorization: Bearer ${{ env.JENKINS_CD_SECRET }}" \
          --data-urlencode "GIT_BRANCH=$GIT_BRANCH"
